### ISSUE TITLE
[Before release] UI pass

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/scale-workshop#109]
_Sevish — Today at 4:31 PM_

> starting to think we need to import some kind of CSS reset
> because I'm seeing ugly differences between browsers
> will look into this for the later UI pass

**Comment by SeanArchibald** [comment]
In Firefox, the placement of some control elements (e.g. 'flip' button on rank 2 generator modal) are caused by widths of elements being larger than half of the container element width. This doesn't affect Chrome/Chromium.

Possible solution is to set a smaller width for those elements in base.css and then add missing `<div class="control-group"><div class="control"> x </div></div>` where needed to fix the side effects (e.g. the fields in Analysis > Chord analysis)
