### ISSUE TITLE
Use a decimal comma for ratios in the tuning table

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/scale-workshop#376]
_This is a request for feedback._

**Pro:** Consistent with our input syntax.
**Con:** Incorrectly localized.

 The solution should be escalated to #270 and #284 .

**Comment by LiftPizzas** [comment]
Is the symbol is separating the ones and tenths digits in a number?

**Comment by frostburn** [comment]
> Is the symbol is separating the ones and tenths digits in a number?

That's what we're talking about here. We don't do thousands grouping at the moment.

**Comment by frostburn** [comment]
Currently we don't dynamically localize, but we might in the future when we internationalize (translate the application).

**Comment by forrcaho** [comment]
I definitely find the comma for a decimal point confusing, even though I know it's used in Europe. I don't think the fact that it's used in the input format is that relevant, because the input format is basically its own DSL. This is a table of decimal numbers, and I'd certainly prefer that they looked like decimal numbers to my American self.

I'd be happy to use commas _for now_, if we fix it later as a part of implementing localization.

**Comment by frostburn** [comment]
I'm sensing a bias towards localization. We only do pseudo-american localization (i.e. use decimal dot, but don't group thousands) at the moment so let's stick to that and remove commas from the matrix.
