### ISSUE TITLE
Merge offset (keep) produces impossible scales with negative offset

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/scale-workshop#511]
To reproduce enter `2/1` as your scale and `1/3` as your offset in the dialog. Use **keep** as the value for **overflow** and press OK.

### Observed behaviour
The displayed scale data doesn't change, but unison drops to `0.333`.

### Expected behaviour
???

**Comment by arseniiv** [comment]
Expected behavior for the *Keep* mode might be this, given it can mess with the period already:

* At first, the scale is implicitly `1/1 2/1`.
* Then we merge `1/3`-offset copy, keeping all: `1/3 1/1 2/3 2/1`.
* *Then* we rescale data for the first pitch become unison again: `1/1 3/1 2/1 6/1`.
* Now we drop the unison, making it implicit again (huh, I get floating-point vibes now, with implicit 1 in mantissa used to store one bit more of it). Finally: `3/1 2/1 6/1`.

**Comment by frostburn** [comment]
I think the generic solution might be this:

- Given a scale `a;b;c;d;e;`
- Add in the implicit `1`
- Pop off the equave -> `1;a;b;c;d;`
- Merge an offset copy of this with the given overflow behaviour (comparing agains `e` if need be)
- Sort
- shift out the `1`
- push the `e` back on.
