### ISSUE TITLE
Always include note labels in .scl output

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/scale-workshop#545]
**frostburn** — _Today at 8:58 AM_

> Scala files are basically just lists of cents. If you ignore the headers it's pretty human-readable if you ask me. 

**zastari** — _Today at 8:58 AM_

> the main complaint for things like 159 edo is not having the step values commented in for you so you'd need to do something like turn on line numbers in a text editor

The solution is to add tuning table note labels after the cent lines in the file output.
Key colors can be listed in a comment after the main output.

**Comment by frostburn** [comment]
**Vynce** — _Today at 9:02 AM_

> then you could have a file with your cents, the note "name" and scale degree, and maybe even a few selected JI near-equivalencies ... locally.

**frostburn** — _Today at 9:04 AM_

> That might get cluttered, but I'll think about offering the option to export fully annotated .scl.

Make .scl export a proper modal, basically.

**Comment by arseniiv** [comment]
So what do we need in this modal:

- [checkbox] include interval expression (like `41\159` for an edo)
- [checkbox] include the color
- [checkbox] include scale degree
- [checkbox] include closest JI intervals
  - [???] something about choosing them

Their order though might be an issue. Maybe something like a format string with variables would be acceptable? (Or it can be an advanced option which is filled in by tweaking simple options from above.)

Not assigning myself just yet because I have no clue what exactly is the target behavior (and look) (and yeah we can ignore JI approximations at first, at least I won’t touch them right away).

**Comment by frostburn** [comment]
Are we doing this in the version 2 series where the interval labels are somewhat nebulous and annoying to work with? In SW3 I would add checkboxes for `scale.labels`, `scale.colors` and scale degrees. A proficient SonicWeaver could put the closest JI intervals into the label strings (or that could be a separate issue about a modification modal that just does helpful labeling stuff).

**Comment by arseniiv** [comment]
I was about targeting SW3. What do you think about ordering, can it be fixed (and which one, then) or how to allow changing it? ~~Via a list with 6 entries.~~

**Comment by frostburn** [comment]
I suggest 3 checkboxes for degrees, labels and colors in that order. It's a good start and an UX designer can always tweak the order later and devs can add more options in the future.

**Comment by frostburn** [comment]
Most text editors can show line numbers so power users can either delete the boilerplate or learn how to program custom labels using SonicWeave. Closing as good enough.

**Comment by arseniiv** [comment]
Sorry I didn’t proceed myself 😶
