### ISSUE TITLE
Reserve capital letters and capital+digit as words for future use

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/scale-workshop#686]

**Comment by frostburn** [comment]
**pinkanberry** — _Today at 5:07 PM_

> also any uppercase letter followed by some lowercase letter is potentially [note][accidental modifier] which is another reason to reserve at least a subset of 2-letter stuff

**Comment by osmiumic** [comment]
i suggest that the minimal things that it would be reasonable to reserve are:
* capital letters
* capital letters followed by any digit or lowercase letter (for example if you ever want to use 2-letter greek letter names or for things like Eb); if lowercase letter then followed by any digit
however it seems simpler to me to reserve *all* 2-character combinations except for "two lowercase letters" (eg useful for various naming styles)... it might be useful to document all single-letter variable names that are reserved (since you mentioned you dont wanna reserve *everything* < 3 characters); for example:

a = augmented (or semi@ in diamond MOS)
b = flat
d = diminished or semiflat
e = semi& in diamond MOS
h = (smth to do with) harmonic/naturals/etc.?
t = semisharp
v = down (corresponding up is ^)

these are all the potential things i can think of but you might think of more to add

**Comment by frostburn** [comment]
I'm not going to reserve lowercase single character identifiers because accidentals must be attached to something. Currently `v` is not an operator `v{...}` is.

**Comment by frostburn** [comment]
Wrong repository, by the way. :upside_down_face:
